#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SimpleApp.Resource", IsApplication=true)]

namespace SimpleApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int blue = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int green = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int grey = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int red = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int white = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int maggray = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int CancelButton = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int DeleteButton = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int IdTextBox = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int LayoutRoot = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int NameTextBox = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int SaveButton = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int StatusTextBox = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int ApplicationName = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int Cancel = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int CustomerId = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int CustomerName = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int Deleting = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Error = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int Loading = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int MarkForDelete = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int Save = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int Saving = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int Status = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
